### ISSUE TITLE
can this pacake generate C cfg?  

### ISSUE THREAD

**Issue by leslielee619** [bdusell/pycfg#1]
now i have a assignment which is to generate C cfg and its Du path. now i could use another package generate C AST, but i dont know how to convert it to cfg

**Comment by bdusell** [comment]
I'm not sure I understand your question, but if you have a corpus of ASTs for C code, you could convert it to a CFG by looking at all of the interior nodes in the trees and creating CFG rules based on the types of the parent and children nodes. This package won't do that for you, but it could help you parse C code once you have the CFG.

**Comment by leslielee619** [comment]
okay，thanks for your reply. cause i dont use english as usual communication, so its difficult for me to express my idea in english. I'll try my best to convert c AST to c CFG. 
In addition,i use  package  《pycparser》 to convert c source code to c AST.

**Comment by bdusell** [comment]
别客气。加油。

**Comment by leslielee619** [comment]
Im major in mechainesm, but i choose a course which called《Software source code analysis》, and teacher give us an assignment which is to convert C source code to C CFG and Du Path. 
and i just find a package can convert C source code to C AST, so i think can i use the information in AST, and convert it to CFG. 
are you chinese? or you just use google translate?

**Comment by bdusell** [comment]
The C language is probably simple enough that you could do the conversion by hand, unless the assignment is to write a program to do it.

我不是中国人，可是我上了一些中文课。

**Comment by leslielee619** [comment]
> The C language is probably simple enough that you could do the conversion by hand, unless the assignment is to write a program to do it.
> 我不是中国人，可是我上了一些中文课。

哈哈 厉害，加油。
老师给的任务是，随便给一段c代码 然后生成其cfg和du path，但是我没学过编译原理，而且这不是我的专业领域，我熟悉力学，机械相关的。

**Comment by leslielee619** [comment]
of course, teacher let us to achieve by programming not by hand.
